#!/bin/sh

if [ ${SCAMPER_ENABLED} ==  "true" ]
 then

if [ ! -d ${INSTALL_ROOT}\${distFilesRoot}/bin/config2 ]
  then
  mkdir ${INSTALL_ROOT}\${distFilesRoot}/bin/config2
  echo "Creating directory " ${INSTALL_ROOT}\${distFilesRoot}/bin/config2
fi


. ${INSTALL_ROOT}\${distFilesRoot}/bin/scamper.sh

#Check to see if the scamper.sh script executed without errors.
#If an error occurred, then exit, stop the install and cause a failed install.
if [ ! $? -eq 0   ]
 then
 exit $?
fi

echo "Finished Scamper file generation"
fi
cd ../../common
exec sh -x ./install_postproc.sh
