/*******************************************************************************
 * Copyright (c) 2016 AT&T Intellectual Property. All rights reserved.
 *******************************************************************************/
package ajsc.utils;

//
//This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
//See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
//Any modifications to this file will be lost upon recompilation of the source schema. 
//Generated on: 2014.08.18 at 11:31:11 AM EDT 
//

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
* ExceptionInfo class for service and policy exceptions as per the northbound API standards.
* 
* <p>Java class for ExceptionInfo complex type.
* 
* <p>The following schema fragment specifies the expected content contained within this class.
* 
* <pre>
* &lt;complexType name="ExceptionInfo">
*   &lt;complexContent>
*     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*       &lt;sequence>
*         &lt;element name="MessageId" type="{http://www.w3.org/2001/XMLSchema}string"/>
*         &lt;element name="Text" type="{http://www.w3.org/2001/XMLSchema}string"/>
*         &lt;element name="Variables" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
*       &lt;/sequence>
*     &lt;/restriction>
*   &lt;/complexContent>
* &lt;/complexType>
* </pre>
* 
* 
*/
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExceptionInfo", propOrder = {
 "messageId",
 "text",
 "variables"
})
public class ExceptionInfo
 implements Serializable
{

 private final static long serialVersionUID = 100L;
 @XmlElement(name = "MessageId", required = true)
 protected String messageId;
 @XmlElement(name = "Text", required = true)
 protected String text;
 @XmlElement(name = "Variables")
 protected List<String> variables;

 /**
  * Gets the value of the messageId property.
  * 
  * @return
  *     possible object is
  *     {@link String }
  *     
  */
 public String getMessageId() {
     return messageId;
 }

 /**
  * Sets the value of the messageId property.
  * 
  * @param value
  *     allowed object is
  *     {@link String }
  *     
  */
 public void setMessageId(String value) {
     this.messageId = value;
 }

 /**
  * Gets the value of the text property.
  * 
  * @return
  *     possible object is
  *     {@link String }
  *     
  */
 public String getText() {
     return text;
 }

 /**
  * Sets the value of the text property.
  * 
  * @param value
  *     allowed object is
  *     {@link String }
  *     
  */
 public void setText(String value) {
     this.text = value;
 }

 /**
  * Gets the value of the variables property.
  * 
  * <p>
  * This accessor method returns a reference to the live list,
  * not a snapshot. Therefore any modification you make to the
  * returned list will be present inside the JAXB object.
  * This is why there is not a <CODE>set</CODE> method for the variables property.
  * 
  * <p>
  * For example, to add a new item, do as follows:
  * <pre>
  *    getVariables().add(newItem);
  * </pre>
  * 
  * 
  * <p>
  * Objects of the following type(s) are allowed in the list
  * {@link String }
  * 
  * 
  */
 public List<String> getVariables() {
     if (variables == null) {
         variables = new ArrayList<String>();
     }
     return this.variables;
 }

}
