/*******************************************************************************
 * Copyright (c) 2016 AT&T Intellectual Property. All rights reserved.
 *******************************************************************************/
package ajsc.utils;

//
//This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
//See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
//Any modifications to this file will be lost upon recompilation of the source schema. 
//Generated on: 2014.08.18 at 11:31:11 AM EDT 
//



import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
* API request error type.
* 
* <p>Java class for RequestErrorInfo complex type.
* 
* <p>The following schema fragment specifies the expected content contained within this class.
* 
* <pre>
* &lt;complexType name="RequestErrorInfo">
*   &lt;complexContent>
*     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*       &lt;choice>
*         &lt;element name="ServiceException" type="{http://csi.cingular.com/CSI/Namespaces/Rest/RequestError.xsd}ExceptionInfo"/>
*         &lt;element name="PolicyException" type="{http://csi.cingular.com/CSI/Namespaces/Rest/RequestError.xsd}ExceptionInfo"/>
*       &lt;/choice>
*     &lt;/restriction>
*   &lt;/complexContent>
* &lt;/complexType>
* </pre>
* 
* 
*/
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RequestErrorInfo", propOrder = {
 "serviceException",
 "policyException"
})
public class RequestErrorInfo
 implements Serializable
{

 private final static long serialVersionUID = 100L;
 @XmlElement(name = "ServiceException")
 protected ExceptionInfo serviceException;
 @XmlElement(name = "PolicyException")
 protected ExceptionInfo policyException;

 /**
  * Gets the value of the serviceException property.
  * 
  * @return
  *     possible object is
  *     {@link ExceptionInfo }
  *     
  */
 public ExceptionInfo getServiceException() {
     return serviceException;
 }

 /**
  * Sets the value of the serviceException property.
  * 
  * @param value
  *     allowed object is
  *     {@link ExceptionInfo }
  *     
  */
 public void setServiceException(ExceptionInfo value) {
     this.serviceException = value;
 }

 /**
  * Gets the value of the policyException property.
  * 
  * @return
  *     possible object is
  *     {@link ExceptionInfo }
  *     
  */
 public ExceptionInfo getPolicyException() {
     return policyException;
 }

 /**
  * Sets the value of the policyException property.
  * 
  * @param value
  *     allowed object is
  *     {@link ExceptionInfo }
  *     
  */
 public void setPolicyException(ExceptionInfo value) {
     this.policyException = value;
 }

}
